// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgp3k-mBlb0giVuyG6KQ7lqbV7FpPzXtQ',
    appId: '1:153564388170:web:7d455d0a530fc4599affb3',
    messagingSenderId: '153564388170',
    projectId: 'todo-17828',
    authDomain: 'todo-17828.firebaseapp.com',
    storageBucket: 'todo-17828.appspot.com',
    measurementId: 'G-GLFP7NCVPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmnOmlQNRqv1ywnWZQT_VPmSJv-SqIHIM',
    appId: '1:153564388170:android:476127c876cfe9fa9affb3',
    messagingSenderId: '153564388170',
    projectId: 'todo-17828',
    storageBucket: 'todo-17828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIspnbzXFjHzQS7AvdKCjHxiHB9UE4ZME',
    appId: '1:153564388170:ios:b9e38c39043e0d2a9affb3',
    messagingSenderId: '153564388170',
    projectId: 'todo-17828',
    storageBucket: 'todo-17828.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIspnbzXFjHzQS7AvdKCjHxiHB9UE4ZME',
    appId: '1:153564388170:ios:a74c66d6a8804c419affb3',
    messagingSenderId: '153564388170',
    projectId: 'todo-17828',
    storageBucket: 'todo-17828.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
